/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AdvisorsRouteImport } from './routes/advisors'
import { Route as AmbassadorRouteImport } from './routes/ambassador'
import { Route as ArchiveRouteImport } from './routes/archive'
import { Route as ChaptersRouteImport } from './routes/chapters'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as EditorRouteImport } from './routes/editor'
import { Route as EditorsRouteImport } from './routes/editors'
import { Route as EventsRouteImport } from './routes/events'
import { Route as GuidanceRouteImport } from './routes/guidance'
import { Route as GuidelinesRouteImport } from './routes/guidelines'
import { Route as InitialReviewerRouteImport } from './routes/initial-reviewer'
import { Route as LoginRouteImport } from './routes/login'
import { Route as MetricsRouteImport } from './routes/metrics'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as ResubmitRouteImport } from './routes/resubmit'
import { Route as ReviewRouteImport } from './routes/review'
import { Route as SearchRouteImport } from './routes/search'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as TeamRouteImport } from './routes/team'
import { Route as TrackRouteImport } from './routes/track'
import { Route as AdminChaptersRouteImport } from './routes/admin.chapters'
import { Route as AdminSubmissionsRouteImport } from './routes/admin.submissions'
import { Route as ArticleSlugRouteImport } from './routes/article.$slug'
import { Route as ArticlesSlugRouteImport } from './routes/articles.$slug'
import { Route as ChaptersSlugRouteImport } from './routes/chapters.$slug'
import { Route as SubmitIndexRouteImport } from './routes/submit.index'
import { Route as SubmitApplyRouteImport } from './routes/submit.apply'
import { Route as ApiPublicAssignInitialReviewersRouteImport } from './routes/api/public/assign-initial-reviewers'
import { Route as ApiPublicRefreshCitationsRouteImport } from './routes/api/public/refresh-citations'
import { Route as ApiPublicReviewRemindersRouteImport } from './routes/api/public/review-reminders'
import { Route as LovableEmailTransactionalPreviewRouteImport } from './routes/lovable/email/transactional/preview'
import { Route as ApiPublicArticleSlugPdfRouteImport } from './routes/api/public/article.$slug.pdf'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AdvisorsRoute = AdvisorsRouteImport.update({
  id: '/advisors',
  path: '/advisors',
  getParentRoute: () => rootRouteImport,
} as any)
const AmbassadorRoute = AmbassadorRouteImport.update({
  id: '/ambassador',
  path: '/ambassador',
  getParentRoute: () => rootRouteImport,
} as any)
const ArchiveRoute = ArchiveRouteImport.update({
  id: '/archive',
  path: '/archive',
  getParentRoute: () => rootRouteImport,
} as any)
const ChaptersRoute = ChaptersRouteImport.update({
  id: '/chapters',
  path: '/chapters',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const EditorRoute = EditorRouteImport.update({
  id: '/editor',
  path: '/editor',
  getParentRoute: () => rootRouteImport,
} as any)
const EditorsRoute = EditorsRouteImport.update({
  id: '/editors',
  path: '/editors',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsRoute = EventsRouteImport.update({
  id: '/events',
  path: '/events',
  getParentRoute: () => rootRouteImport,
} as any)
const GuidanceRoute = GuidanceRouteImport.update({
  id: '/guidance',
  path: '/guidance',
  getParentRoute: () => rootRouteImport,
} as any)
const GuidelinesRoute = GuidelinesRouteImport.update({
  id: '/guidelines',
  path: '/guidelines',
  getParentRoute: () => rootRouteImport,
} as any)
const InitialReviewerRoute = InitialReviewerRouteImport.update({
  id: '/initial-reviewer',
  path: '/initial-reviewer',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const MetricsRoute = MetricsRouteImport.update({
  id: '/metrics',
  path: '/metrics',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const ResubmitRoute = ResubmitRouteImport.update({
  id: '/resubmit',
  path: '/resubmit',
  getParentRoute: () => rootRouteImport,
} as any)
const ReviewRoute = ReviewRouteImport.update({
  id: '/review',
  path: '/review',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const TeamRoute = TeamRouteImport.update({
  id: '/team',
  path: '/team',
  getParentRoute: () => rootRouteImport,
} as any)
const TrackRoute = TrackRouteImport.update({
  id: '/track',
  path: '/track',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminChaptersRoute = AdminChaptersRouteImport.update({
  id: '/admin/chapters',
  path: '/admin/chapters',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminSubmissionsRoute = AdminSubmissionsRouteImport.update({
  id: '/admin/submissions',
  path: '/admin/submissions',
  getParentRoute: () => rootRouteImport,
} as any)
const ArticleSlugRoute = ArticleSlugRouteImport.update({
  id: '/article/$slug',
  path: '/article/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ArticlesSlugRoute = ArticlesSlugRouteImport.update({
  id: '/articles/$slug',
  path: '/articles/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ChaptersSlugRoute = ChaptersSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => ChaptersRoute,
} as any)
const SubmitIndexRoute = SubmitIndexRouteImport.update({
  id: '/submit/',
  path: '/submit/',
  getParentRoute: () => rootRouteImport,
} as any)
const SubmitApplyRoute = SubmitApplyRouteImport.update({
  id: '/submit/apply',
  path: '/submit/apply',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicAssignInitialReviewersRoute =
  ApiPublicAssignInitialReviewersRouteImport.update({
    id: '/api/public/assign-initial-reviewers',
    path: '/api/public/assign-initial-reviewers',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicRefreshCitationsRoute =
  ApiPublicRefreshCitationsRouteImport.update({
    id: '/api/public/refresh-citations',
    path: '/api/public/refresh-citations',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicReviewRemindersRoute =
  ApiPublicReviewRemindersRouteImport.update({
    id: '/api/public/review-reminders',
    path: '/api/public/review-reminders',
    getParentRoute: () => rootRouteImport,
  } as any)
const LovableEmailTransactionalPreviewRoute =
  LovableEmailTransactionalPreviewRouteImport.update({
    id: '/lovable/email/transactional/preview',
    path: '/lovable/email/transactional/preview',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicArticleSlugPdfRoute = ApiPublicArticleSlugPdfRouteImport.update({
  id: '/api/public/article/$slug/pdf',
  path: '/api/public/article/$slug/pdf',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/advisors': typeof AdvisorsRoute
  '/ambassador': typeof AmbassadorRoute
  '/archive': typeof ArchiveRoute
  '/chapters': typeof ChaptersRouteWithChildren
  '/contact': typeof ContactRoute
  '/editor': typeof EditorRoute
  '/editors': typeof EditorsRoute
  '/events': typeof EventsRoute
  '/guidance': typeof GuidanceRoute
  '/guidelines': typeof GuidelinesRoute
  '/initial-reviewer': typeof InitialReviewerRoute
  '/login': typeof LoginRoute
  '/metrics': typeof MetricsRoute
  '/privacy': typeof PrivacyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/resubmit': typeof ResubmitRoute
  '/review': typeof ReviewRoute
  '/search': typeof SearchRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/team': typeof TeamRoute
  '/track': typeof TrackRoute
  '/admin/chapters': typeof AdminChaptersRoute
  '/admin/submissions': typeof AdminSubmissionsRoute
  '/article/$slug': typeof ArticleSlugRoute
  '/articles/$slug': typeof ArticlesSlugRoute
  '/chapters/$slug': typeof ChaptersSlugRoute
  '/submit/apply': typeof SubmitApplyRoute
  '/submit/': typeof SubmitIndexRoute
  '/api/public/assign-initial-reviewers': typeof ApiPublicAssignInitialReviewersRoute
  '/api/public/refresh-citations': typeof ApiPublicRefreshCitationsRoute
  '/api/public/review-reminders': typeof ApiPublicReviewRemindersRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
  '/api/public/article/$slug/pdf': typeof ApiPublicArticleSlugPdfRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/advisors': typeof AdvisorsRoute
  '/ambassador': typeof AmbassadorRoute
  '/archive': typeof ArchiveRoute
  '/chapters': typeof ChaptersRouteWithChildren
  '/contact': typeof ContactRoute
  '/editor': typeof EditorRoute
  '/editors': typeof EditorsRoute
  '/events': typeof EventsRoute
  '/guidance': typeof GuidanceRoute
  '/guidelines': typeof GuidelinesRoute
  '/initial-reviewer': typeof InitialReviewerRoute
  '/login': typeof LoginRoute
  '/metrics': typeof MetricsRoute
  '/privacy': typeof PrivacyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/resubmit': typeof ResubmitRoute
  '/review': typeof ReviewRoute
  '/search': typeof SearchRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/team': typeof TeamRoute
  '/track': typeof TrackRoute
  '/admin/chapters': typeof AdminChaptersRoute
  '/admin/submissions': typeof AdminSubmissionsRoute
  '/article/$slug': typeof ArticleSlugRoute
  '/articles/$slug': typeof ArticlesSlugRoute
  '/chapters/$slug': typeof ChaptersSlugRoute
  '/submit/apply': typeof SubmitApplyRoute
  '/submit': typeof SubmitIndexRoute
  '/api/public/assign-initial-reviewers': typeof ApiPublicAssignInitialReviewersRoute
  '/api/public/refresh-citations': typeof ApiPublicRefreshCitationsRoute
  '/api/public/review-reminders': typeof ApiPublicReviewRemindersRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
  '/api/public/article/$slug/pdf': typeof ApiPublicArticleSlugPdfRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/advisors': typeof AdvisorsRoute
  '/ambassador': typeof AmbassadorRoute
  '/archive': typeof ArchiveRoute
  '/chapters': typeof ChaptersRouteWithChildren
  '/contact': typeof ContactRoute
  '/editor': typeof EditorRoute
  '/editors': typeof EditorsRoute
  '/events': typeof EventsRoute
  '/guidance': typeof GuidanceRoute
  '/guidelines': typeof GuidelinesRoute
  '/initial-reviewer': typeof InitialReviewerRoute
  '/login': typeof LoginRoute
  '/metrics': typeof MetricsRoute
  '/privacy': typeof PrivacyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/resubmit': typeof ResubmitRoute
  '/review': typeof ReviewRoute
  '/search': typeof SearchRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/team': typeof TeamRoute
  '/track': typeof TrackRoute
  '/admin/chapters': typeof AdminChaptersRoute
  '/admin/submissions': typeof AdminSubmissionsRoute
  '/article/$slug': typeof ArticleSlugRoute
  '/articles/$slug': typeof ArticlesSlugRoute
  '/chapters/$slug': typeof ChaptersSlugRoute
  '/submit/apply': typeof SubmitApplyRoute
  '/submit/': typeof SubmitIndexRoute
  '/api/public/assign-initial-reviewers': typeof ApiPublicAssignInitialReviewersRoute
  '/api/public/refresh-citations': typeof ApiPublicRefreshCitationsRoute
  '/api/public/review-reminders': typeof ApiPublicReviewRemindersRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
  '/api/public/article/$slug/pdf': typeof ApiPublicArticleSlugPdfRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/advisors'
    | '/ambassador'
    | '/archive'
    | '/chapters'
    | '/contact'
    | '/editor'
    | '/editors'
    | '/events'
    | '/guidance'
    | '/guidelines'
    | '/initial-reviewer'
    | '/login'
    | '/metrics'
    | '/privacy'
    | '/reset-password'
    | '/resubmit'
    | '/review'
    | '/search'
    | '/sitemap.xml'
    | '/team'
    | '/track'
    | '/admin/chapters'
    | '/admin/submissions'
    | '/article/$slug'
    | '/articles/$slug'
    | '/chapters/$slug'
    | '/submit/apply'
    | '/submit/'
    | '/api/public/assign-initial-reviewers'
    | '/api/public/refresh-citations'
    | '/api/public/review-reminders'
    | '/lovable/email/transactional/preview'
    | '/api/public/article/$slug/pdf'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/advisors'
    | '/ambassador'
    | '/archive'
    | '/chapters'
    | '/contact'
    | '/editor'
    | '/editors'
    | '/events'
    | '/guidance'
    | '/guidelines'
    | '/initial-reviewer'
    | '/login'
    | '/metrics'
    | '/privacy'
    | '/reset-password'
    | '/resubmit'
    | '/review'
    | '/search'
    | '/sitemap.xml'
    | '/team'
    | '/track'
    | '/admin/chapters'
    | '/admin/submissions'
    | '/article/$slug'
    | '/articles/$slug'
    | '/chapters/$slug'
    | '/submit/apply'
    | '/submit'
    | '/api/public/assign-initial-reviewers'
    | '/api/public/refresh-citations'
    | '/api/public/review-reminders'
    | '/lovable/email/transactional/preview'
    | '/api/public/article/$slug/pdf'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/advisors'
    | '/ambassador'
    | '/archive'
    | '/chapters'
    | '/contact'
    | '/editor'
    | '/editors'
    | '/events'
    | '/guidance'
    | '/guidelines'
    | '/initial-reviewer'
    | '/login'
    | '/metrics'
    | '/privacy'
    | '/reset-password'
    | '/resubmit'
    | '/review'
    | '/search'
    | '/sitemap.xml'
    | '/team'
    | '/track'
    | '/admin/chapters'
    | '/admin/submissions'
    | '/article/$slug'
    | '/articles/$slug'
    | '/chapters/$slug'
    | '/submit/apply'
    | '/submit/'
    | '/api/public/assign-initial-reviewers'
    | '/api/public/refresh-citations'
    | '/api/public/review-reminders'
    | '/lovable/email/transactional/preview'
    | '/api/public/article/$slug/pdf'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AdvisorsRoute: typeof AdvisorsRoute
  AmbassadorRoute: typeof AmbassadorRoute
  ArchiveRoute: typeof ArchiveRoute
  ChaptersRoute: typeof ChaptersRouteWithChildren
  ContactRoute: typeof ContactRoute
  EditorRoute: typeof EditorRoute
  EditorsRoute: typeof EditorsRoute
  EventsRoute: typeof EventsRoute
  GuidanceRoute: typeof GuidanceRoute
  GuidelinesRoute: typeof GuidelinesRoute
  InitialReviewerRoute: typeof InitialReviewerRoute
  LoginRoute: typeof LoginRoute
  MetricsRoute: typeof MetricsRoute
  PrivacyRoute: typeof PrivacyRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  ResubmitRoute: typeof ResubmitRoute
  ReviewRoute: typeof ReviewRoute
  SearchRoute: typeof SearchRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  TeamRoute: typeof TeamRoute
  TrackRoute: typeof TrackRoute
  AdminChaptersRoute: typeof AdminChaptersRoute
  AdminSubmissionsRoute: typeof AdminSubmissionsRoute
  ArticleSlugRoute: typeof ArticleSlugRoute
  ArticlesSlugRoute: typeof ArticlesSlugRoute
  SubmitApplyRoute: typeof SubmitApplyRoute
  SubmitIndexRoute: typeof SubmitIndexRoute
  ApiPublicAssignInitialReviewersRoute: typeof ApiPublicAssignInitialReviewersRoute
  ApiPublicRefreshCitationsRoute: typeof ApiPublicRefreshCitationsRoute
  ApiPublicReviewRemindersRoute: typeof ApiPublicReviewRemindersRoute
  LovableEmailTransactionalPreviewRoute: typeof LovableEmailTransactionalPreviewRoute
  ApiPublicArticleSlugPdfRoute: typeof ApiPublicArticleSlugPdfRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/advisors': {
      id: '/advisors'
      path: '/advisors'
      fullPath: '/advisors'
      preLoaderRoute: typeof AdvisorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ambassador': {
      id: '/ambassador'
      path: '/ambassador'
      fullPath: '/ambassador'
      preLoaderRoute: typeof AmbassadorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/archive': {
      id: '/archive'
      path: '/archive'
      fullPath: '/archive'
      preLoaderRoute: typeof ArchiveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chapters': {
      id: '/chapters'
      path: '/chapters'
      fullPath: '/chapters'
      preLoaderRoute: typeof ChaptersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/editor': {
      id: '/editor'
      path: '/editor'
      fullPath: '/editor'
      preLoaderRoute: typeof EditorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/editors': {
      id: '/editors'
      path: '/editors'
      fullPath: '/editors'
      preLoaderRoute: typeof EditorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events': {
      id: '/events'
      path: '/events'
      fullPath: '/events'
      preLoaderRoute: typeof EventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guidance': {
      id: '/guidance'
      path: '/guidance'
      fullPath: '/guidance'
      preLoaderRoute: typeof GuidanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guidelines': {
      id: '/guidelines'
      path: '/guidelines'
      fullPath: '/guidelines'
      preLoaderRoute: typeof GuidelinesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/initial-reviewer': {
      id: '/initial-reviewer'
      path: '/initial-reviewer'
      fullPath: '/initial-reviewer'
      preLoaderRoute: typeof InitialReviewerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/metrics': {
      id: '/metrics'
      path: '/metrics'
      fullPath: '/metrics'
      preLoaderRoute: typeof MetricsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resubmit': {
      id: '/resubmit'
      path: '/resubmit'
      fullPath: '/resubmit'
      preLoaderRoute: typeof ResubmitRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/review': {
      id: '/review'
      path: '/review'
      fullPath: '/review'
      preLoaderRoute: typeof ReviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/team': {
      id: '/team'
      path: '/team'
      fullPath: '/team'
      preLoaderRoute: typeof TeamRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/track': {
      id: '/track'
      path: '/track'
      fullPath: '/track'
      preLoaderRoute: typeof TrackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/chapters': {
      id: '/admin/chapters'
      path: '/admin/chapters'
      fullPath: '/admin/chapters'
      preLoaderRoute: typeof AdminChaptersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/submissions': {
      id: '/admin/submissions'
      path: '/admin/submissions'
      fullPath: '/admin/submissions'
      preLoaderRoute: typeof AdminSubmissionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/article/$slug': {
      id: '/article/$slug'
      path: '/article/$slug'
      fullPath: '/article/$slug'
      preLoaderRoute: typeof ArticleSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/articles/$slug': {
      id: '/articles/$slug'
      path: '/articles/$slug'
      fullPath: '/articles/$slug'
      preLoaderRoute: typeof ArticlesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chapters/$slug': {
      id: '/chapters/$slug'
      path: '/$slug'
      fullPath: '/chapters/$slug'
      preLoaderRoute: typeof ChaptersSlugRouteImport
      parentRoute: typeof ChaptersRoute
    }
    '/submit/': {
      id: '/submit/'
      path: '/submit'
      fullPath: '/submit/'
      preLoaderRoute: typeof SubmitIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/submit/apply': {
      id: '/submit/apply'
      path: '/submit/apply'
      fullPath: '/submit/apply'
      preLoaderRoute: typeof SubmitApplyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/assign-initial-reviewers': {
      id: '/api/public/assign-initial-reviewers'
      path: '/api/public/assign-initial-reviewers'
      fullPath: '/api/public/assign-initial-reviewers'
      preLoaderRoute: typeof ApiPublicAssignInitialReviewersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/refresh-citations': {
      id: '/api/public/refresh-citations'
      path: '/api/public/refresh-citations'
      fullPath: '/api/public/refresh-citations'
      preLoaderRoute: typeof ApiPublicRefreshCitationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/review-reminders': {
      id: '/api/public/review-reminders'
      path: '/api/public/review-reminders'
      fullPath: '/api/public/review-reminders'
      preLoaderRoute: typeof ApiPublicReviewRemindersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/transactional/preview': {
      id: '/lovable/email/transactional/preview'
      path: '/lovable/email/transactional/preview'
      fullPath: '/lovable/email/transactional/preview'
      preLoaderRoute: typeof LovableEmailTransactionalPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/article/$slug/pdf': {
      id: '/api/public/article/$slug/pdf'
      path: '/api/public/article/$slug/pdf'
      fullPath: '/api/public/article/$slug/pdf'
      preLoaderRoute: typeof ApiPublicArticleSlugPdfRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface ChaptersRouteChildren {
  ChaptersSlugRoute: typeof ChaptersSlugRoute
}

const ChaptersRouteChildren: ChaptersRouteChildren = {
  ChaptersSlugRoute: ChaptersSlugRoute,
}

const ChaptersRouteWithChildren = ChaptersRoute._addFileChildren(
  ChaptersRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AdvisorsRoute: AdvisorsRoute,
  AmbassadorRoute: AmbassadorRoute,
  ArchiveRoute: ArchiveRoute,
  ChaptersRoute: ChaptersRouteWithChildren,
  ContactRoute: ContactRoute,
  EditorRoute: EditorRoute,
  EditorsRoute: EditorsRoute,
  EventsRoute: EventsRoute,
  GuidanceRoute: GuidanceRoute,
  GuidelinesRoute: GuidelinesRoute,
  InitialReviewerRoute: InitialReviewerRoute,
  LoginRoute: LoginRoute,
  MetricsRoute: MetricsRoute,
  PrivacyRoute: PrivacyRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  ResubmitRoute: ResubmitRoute,
  ReviewRoute: ReviewRoute,
  SearchRoute: SearchRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  TeamRoute: TeamRoute,
  TrackRoute: TrackRoute,
  AdminChaptersRoute: AdminChaptersRoute,
  AdminSubmissionsRoute: AdminSubmissionsRoute,
  ArticleSlugRoute: ArticleSlugRoute,
  ArticlesSlugRoute: ArticlesSlugRoute,
  SubmitApplyRoute: SubmitApplyRoute,
  SubmitIndexRoute: SubmitIndexRoute,
  ApiPublicAssignInitialReviewersRoute: ApiPublicAssignInitialReviewersRoute,
  ApiPublicRefreshCitationsRoute: ApiPublicRefreshCitationsRoute,
  ApiPublicReviewRemindersRoute: ApiPublicReviewRemindersRoute,
  LovableEmailTransactionalPreviewRoute: LovableEmailTransactionalPreviewRoute,
  ApiPublicArticleSlugPdfRoute: ApiPublicArticleSlugPdfRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
